name: deployment
on:
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
  # https://github.com/actions/setup-java#caching-packages-dependencies
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "package.json"
      - "index.html"
      - "swa-cli.config.json"
      - "tsconfig.json"
      - "vite.config.ts"
      - ".github/workflows/deployment.yaml"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "20.x"
      - run: cp .nojekyll public
      - run: ls -l public
      - run: git config --global user.email "rock.c.c.hu@gmail.com"
      - run: git config --global user.name "Rock Hu"
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - run: npm install
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: rock-hu/pwa-portal
          BRANCH: gh-pages
          FOLDER: public
